version: '3.8'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pr_review_app:/app/pr_review_app
      - ./shared:/app/shared
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@db:5432/pr-review-db
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
      - db
    command: uvicorn pr_review_app.main:app --log-config pr_review_app/config/logging_config.json --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./celery_worker:/app/celery_worker
      - ./shared:/app/shared
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@db:5432/pr-review-db
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    command: celery -A celery_worker.celery_app:app worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # flower:
  #   image: mher/flower
  #   command: ["flower", "--broker=redis://redis:6379/0"]
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pr-review-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis_data:
  pgdata: 